### ISSUE TITLE
bug/question: wrong TypeScript declarations?

### ISSUE THREAD

**Issue by Znerole** [AlexTorresSk/custom-electron-titlebar#180]
**Describe the bug**
The current TypeScript declarations appear to be wrong to me. Importing `Titlebar` and `Color` doesn't allow proper type usage:

```TypeScript
import { Titlebar } from "custom-electron-titlebar"

const titleBar: Titlebar = new Titlebar()
```

The second statement produces the following error:

```
'Titlebar' refers to a value, but is being used as a type here. Did you mean 'typeof Titlebar'?
```

Contents of `index.d.ts` are:

```TypeScript
import Titlebar from './titlebar';
import { Color } from './common/color';
declare const _default: {
    Titlebar: typeof Titlebar;
    Color: typeof Color;
};
export = _default;
```

This issue is new in 4.x.

**To Reproduce**
1. Create a new TypeScript project
2. Add `custom-electron-titlebar` to the project
3. Import `Titlebar` as shown before

**Expected behavior**
Types should be used "normally".

**Desktop (please complete the following information):**
 - TypeScript version: 4.4.4
 - custom-electron-titlebar version: 4.1.0

**Comment by TheBentoBox** [comment]
Same issue here. To be blunt the typings in this project are not the greatest in general right now.

Another issue is that there's no proper way to import anything other than `Titlebar` and `Color` if you're targeting ECMAScript modules:

These two fail to compile:

![image](https://user-images.githubusercontent.com/6902229/170770111-fa4f588b-f849-4ea0-a308-a09777e8eaa8.png)
![image](https://user-images.githubusercontent.com/6902229/170770072-7470f864-9986-4a2b-b4d7-8545dce9c6bd.png)

While a direct import fails on build since it's not exported by the package:
![image](https://user-images.githubusercontent.com/6902229/170770288-ee06f396-4d7d-48a8-8a76-651352ca8068.png)
![image](https://user-images.githubusercontent.com/6902229/170770318-8f0fba7f-73e7-4178-a630-ae7d543e917b.png)

Is there a reason the main `index` file doesn't export the entirety of the package's API?

**Comment by AlexTorresSk** [comment]
#188 duplicated
