### ISSUE TITLE
error TS6200: Definitions of the following identifiers conflict with those in another file

### ISSUE THREAD

**Issue by BartNetJS** [AlexTorresSk/custom-electron-titlebar#2]
Hi, i got the following compile error when importing  from custom-electron-titlebar

I followed your example for typescript and added it to the renderer.ts

![image](https://user-images.githubusercontent.com/4865355/50564132-d7ad0380-0d22-11e9-8ade-a1885962e009.png)

**Comment by AlexTorresSk** [comment]
@BartNetJS In version 2.0.3 this problem has been resolved, but if the problem persists add `"esModuleInterop": true` to your tsconfig file

**Comment by AlexTorresSk** [comment]
Verify that you are using the correct version. Because there is no error in [this project](https://github.com/AlexTorresSk/custom-electron-titlebar-quickstart).

![image](https://user-images.githubusercontent.com/45916349/50935237-5b5ca380-1439-11e9-9163-e0f7780ddd70.png)

the definition files are inside the **lib** folder

**Comment by AlexTorresSk** [comment]
The **error TS6200** occurs when using typescript in the main electron file. This has been resolved in the latest version ([v2.1.0](https://github.com/AlexTorresSk/custom-electron-titlebar/tree/v2.1.0)) 😃
