### ISSUE TITLE
Titlebar is forcing overflow: auto;

### ISSUE THREAD

**Issue by ivanjeremic** [AlexTorresSk/custom-electron-titlebar#52]
The problem with this Titlebar Framework is that it is hard to work with it since it is part of the viewport and that causes complications like mentioned in the description, If you define in Main.CSS your body to be overflow: hidden; and then you install this framework the css you wrote is useless and the bug is the scrollbar gets forced in your app. The property overflow hidden for the custom-electron-titlebar cannot be used since there is also a bug when using it the whole titlebar gets removed instead of the overflow. 

This framework needs I think to be rebuilt in a way to insert a div and give it a specific Class so the framework injects there the titlebar and also an option to have dynamic CSS since the titlebar for MAC is smaller and to not break to the whole layout everything needs to be adjusted along with the titlebar height.. 

I hope this gets fixed, if there is a solution please let me know for now I can not use it in production.

**Comment by AlexTorresSk** [comment]
Please attach an image or video where you can show what it says

**Comment by ivanjeremic** [comment]
> Please attach an image or video where you can show what it says

Sure I have created a repo with a simple grid layout for you and I added importand comments in the code for you, the first comment is in the index.html at the end of the body in the script tag, and the second comment is on top of the style.css. Here the repo [https://github.com/ivanjeremic/titlebarbug](url)

**Comment by AlexTorresSk** [comment]
When reviewing the code presented in the url, there are several things that are wrong with your code.

First I recommend reading the project options in: https://github.com/AlexTorresSk/custom-electron-titlebar#options, because the overflow option is of type string and in your code it is not used that way and second if you want to add some style to the body of the window add it to the `container-after title bar` class, because this is the div class in which the entire body of the page is added.

**Comment by ivanjeremic** [comment]
You are right, no idea how I missed that the overflow is not of type string in my code, I was looking at the options the whole time! That fixed it for me, Thank you and a nice project! I hope it will be an active project!
