### ISSUE TITLE
Issue with scrolling

### ISSUE THREAD

**Issue by leontepe** [AlexTorresSk/custom-electron-titlebar#90]
I just integrated this package into my project and I am having an issue with scrolling.

When I open an HTML that is scrollable (because it doesn't fit the window size), the titlebar produces double scrollbars. I suppose the titlebar is "pushing the content down", which leads to the actual content window below the titlebar being scrollable as well -- but just _a little bit_. It is only scrollable for like ~32px, which perfectly fits the titlebar.

Is this issue known? Should this be fixed in the titlebar package (here) or locally using any CSS adjustment? It would be lovely if this would work out of the box.

**Comment by ericblade** [comment]
confirming that with me, just dropping this package in results in horizontal and vertical scrollbars that weren't there, previously.  they go away if i resize manually.  i might try forcing an automatic resize to the same as the current size after adding the title bar, and seeing what happens.  I suspect this is because I'm running it in document loaded event, as i load the titlebar in preload.

**Comment by ericblade** [comment]
adding overlay: visible to my project fixed this except for very small windows.
